In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("C:/Users/Admin/Desktop/Bykea/clustered_data.csv")
df.head()

customer_id acquired_by  \
0  5f4c6ec3332a3a434908daeb7425d481     OFFLINE   
1  45708d03d49d042719f0386dc37af61c     OFFLINE   
2  eb08a9964ddd08d3b2ec70d51bbefe5a     OFFLINE   
3  f887e577ad6ed3b78dd4fa4d405d9ae8     OFFLINE   
4  ab02b2539ad27589fdf17bc138e76ddb      ONLINE   

                      acquired_date         transaction_time  product_code  \
0  2017-11-23 18:11:24.687000+00:00  2021-10-23 23:29:00.781            80   
1  2020-01-19 20:46:51.203000+00:00  2021-10-23 23:21:11.122            78   
2  2019-10-09 05:08:01.209000+00:00  2021-10-24 00:17:40.063            78   
3  2018-09-16 05:11:55.127000+00:00  2021-10-23 22:59:03.918            78   
4  2021-06-07 05:50:37.613000+00:00  2021-10-23 22:01:14.746            78   

  parent_region_id  value                   child_region_id  transaction_day  \
0              07B    175  8F1D5D51A8DA48731E42BBF353BFB7D8               23   
1              300     92  1BA53B5BBB76E9903A2CF8FF02C37293               23   
2              300    240  1BA53B5BBB76E9903A2CF8FF02C37293               24   
3              07B    234  729470E813F48EEAB42A800818FDC08E               23   
4              07B    103  3DCC8B4086B582DDB2E5481A5D44CAB4               23   

   transaction_month  ...  transaction_dayofweek  acquired_day  \
0                 10  ...                      5            23   
1                 10  ...                      5            19   
2                 10  ...                      6             9   
3                 10  ...                      5            16   
4                 10  ...                      5             7   

   acquired_month  acquired_year  acquired_dayofweek  customer_total_value  \
0              11           2017                   3                   825   
1               1           2020                   6                  3104   
2              10           2019                   2                  1109   
3               9           2018                   6                  2398   
4               6           2021                   0                   969   

   acquired_by_encoded  product_code_encoded  parent_region_id_encoded  \
0                    0                     4                         0   
1                    0                     2                         2   
2                    0                     2                         2   
3                    0                     2                         0   
4                    1                     2                         0   

   Cluster  
0        0  
1        1  
2        0  
3        0  
4        0  

[5 rows x 21 columns]

In [3]:
df.shape

(1733984, 21)

In [4]:
from sklearn.preprocessing import StandardScaler
# Drop irrelevant columns (if necessary) and keep only the features for classification
X = df.drop(columns=['customer_id', 'acquired_by', 'acquired_date', 'transaction_time', 'product_code', 'parent_region_id', 'child_region_id', 'customer_total_value', 'product_code_encoded', 'Cluster'])
y = df['Cluster']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Define and train a classification model (Random Forest in this example)
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred = rf_model.predict(X_test_scaled)

# Evaluate the performance of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.6661681366254258


In [5]:
from sklearn.metrics import confusion_matrix, classification_report

# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Generate classification report
report = classification_report(y_test, y_pred)
print("Classification Report:")
print(report)

Confusion Matrix:
[[172422  87139]
 [ 86519 174116]]
Classification Report:
              precision    recall  f1-score   support

           0       0.67      0.66      0.67    259561
           1       0.67      0.67      0.67    260635

    accuracy                           0.67    520196
   macro avg       0.67      0.67      0.67    520196
weighted avg       0.67      0.67      0.67    520196



In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Define the parameter grid for hyperparameter tuning
param_grid = {
    'n_estimators': [100, 200, 300],  # Number of trees in the forest
    'max_depth': [None, 5, 10],       # Maximum depth of each tree
    'max_features': ['sqrt', 'log2']  # Number of features to consider at each split
}

# Perform grid search with cross-validation
grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, cv=5)
grid_search.fit(X_train_scaled, y_train)

# Get the best hyperparameters
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

# Use the best model for prediction
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

# Evaluate the performance of the best model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Load your dataset into X and y variables

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Define and initialize the logistic regression model
lr_model = LogisticRegression(random_state=42, multi_class='multinomial')

# Train the model
lr_model.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred = lr_model.predict(X_test)


# Evaluate the performance of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.5000273935472337


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(


In [7]:
from sklearn.metrics import confusion_matrix, classification_report

# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Generate classification report
report = classification_report(y_test, y_pred)
print("Classification Report:")
print(report)

Confusion Matrix:
[[172852    253]
 [173136    556]]
Classification Report:
              precision    recall  f1-score   support

           0       0.50      1.00      0.67    173105
           1       0.69      0.00      0.01    173692

    accuracy                           0.50    346797
   macro avg       0.59      0.50      0.34    346797
weighted avg       0.59      0.50      0.34    346797



In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Load your dataset into X and y variables

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Define and initialize the KNN classifier
k = 5  # Number of neighbors to consider
knn_model = KNeighborsClassifier(n_neighbors=k)

# Train the model
knn_model.fit(X_train_scaled, y_train)

# Make predictions on the test set
y_pred = knn_model.predict(X_test)

# Evaluate the performance of the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(


Accuracy: 0.5007535621188937


In [9]:
from sklearn.metrics import confusion_matrix, classification_report

# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Generate classification report
report = classification_report(y_test, y_pred)
print("Classification Report:")
print(report)

Confusion Matrix:
[[    74 259487]
 [   219 260416]]
Classification Report:
              precision    recall  f1-score   support

           0       0.25      0.00      0.00    259561
           1       0.50      1.00      0.67    260635

    accuracy                           0.50    520196
   macro avg       0.38      0.50      0.33    520196
weighted avg       0.38      0.50      0.33    520196



In [ ]:
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.metrics import accuracy_score

# Initialize the individual classifiers
random_forest = RandomForestClassifier(random_state=42)
xgboost = XGBClassifier(random_state=42)

# Create the ensemble model using VotingClassifier
ensemble_model = VotingClassifier(
    estimators=[('rf', random_forest), ('xgb', xgboost)],
    voting='hard'  # 'hard' for majority voting, 'soft' for weighted voting based on probabilities
)

# Train the ensemble model
ensemble_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = ensemble_model.predict(X_test)

# Evaluate the performance of the ensemble model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

# Generate confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Generate classification report
report = classification_report(y_test, y_pred)
print("Classification Report:")
print(report)

In [5]:
import pickle
with open('rf_model.pkl', 'wb') as file:
    pickle.dump(rf_model, file)

In [7]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)